/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CredentialRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "INSTITUTION_ROLE"
      | "UPGRADE_INTERFACE_VERSION"
      | "addInstitution"
      | "anchorCredentialBatch"
      | "batchCheckRevocation"
      | "getInstitutionInfo"
      | "getMerkleRootInfo"
      | "getRevocationTimestamp"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "institutions"
      | "isInstitution"
      | "isRevoked"
      | "merkleRoots"
      | "proxiableUUID"
      | "removeInstitution"
      | "renounceRole"
      | "revocationTimestamps"
      | "revokeCredential"
      | "revokeRole"
      | "revokedCredentials"
      | "supportsInterface"
      | "totalCredentialsAnchored"
      | "totalInstitutions"
      | "upgradeToAndCall"
      | "version"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CredentialBatchAnchored"
      | "CredentialRevoked"
      | "Initialized"
      | "InstitutionAdded"
      | "InstitutionRemoved"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INSTITUTION_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addInstitution",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "anchorCredentialBatch",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchCheckRevocation",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getInstitutionInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMerkleRootInfo",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRevocationTimestamp",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "institutions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isInstitution",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRevoked",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "merkleRoots",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeInstitution",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revocationTimestamps",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCredential",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokedCredentials",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalCredentialsAnchored",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalInstitutions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INSTITUTION_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addInstitution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "anchorCredentialBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchCheckRevocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInstitutionInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMerkleRootInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRevocationTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "institutions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isInstitution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isRevoked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "merkleRoots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeInstitution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revocationTimestamps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokedCredentials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalCredentialsAnchored",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalInstitutions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export namespace CredentialBatchAnchoredEvent {
  export type InputTuple = [
    merkleRoot: BytesLike,
    institution: AddressLike,
    batchSize: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    merkleRoot: string,
    institution: string,
    batchSize: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    merkleRoot: string;
    institution: string;
    batchSize: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialRevokedEvent {
  export type InputTuple = [
    credentialId: BytesLike,
    institution: AddressLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    credentialId: string,
    institution: string,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    credentialId: string;
    institution: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InstitutionAddedEvent {
  export type InputTuple = [
    institution: AddressLike,
    name: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    institution: string,
    name: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    institution: string;
    name: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InstitutionRemovedEvent {
  export type InputTuple = [institution: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [institution: string, timestamp: bigint];
  export interface OutputObject {
    institution: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CredentialRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CredentialRegistry;
  waitForDeployment(): Promise<this>;

  interface: CredentialRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  INSTITUTION_ROLE: TypedContractMethod<[], [string], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  addInstitution: TypedContractMethod<
    [institution: AddressLike, name: string],
    [void],
    "nonpayable"
  >;

  anchorCredentialBatch: TypedContractMethod<
    [merkleRoot: BytesLike, batchSize: BigNumberish],
    [void],
    "nonpayable"
  >;

  batchCheckRevocation: TypedContractMethod<
    [credentialIds: BytesLike[]],
    [boolean[]],
    "view"
  >;

  getInstitutionInfo: TypedContractMethod<
    [institution: AddressLike],
    [
      [string, boolean, bigint, bigint] & {
        name: string;
        active: boolean;
        registeredDate: bigint;
        totalCredentials: bigint;
      }
    ],
    "view"
  >;

  getMerkleRootInfo: TypedContractMethod<
    [merkleRoot: BytesLike],
    [
      [string, bigint, bigint] & {
        institution: string;
        batchSize: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getRevocationTimestamp: TypedContractMethod<
    [credentialId: BytesLike],
    [bigint],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<[admin: AddressLike], [void], "nonpayable">;

  institutions: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, boolean, bigint, bigint] & {
        name: string;
        active: boolean;
        registeredDate: bigint;
        totalCredentials: bigint;
      }
    ],
    "view"
  >;

  isInstitution: TypedContractMethod<
    [institution: AddressLike],
    [boolean],
    "view"
  >;

  isRevoked: TypedContractMethod<[credentialId: BytesLike], [boolean], "view">;

  merkleRoots: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, boolean] & {
        institution: string;
        batchSize: bigint;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  removeInstitution: TypedContractMethod<
    [institution: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revocationTimestamps: TypedContractMethod<
    [arg0: BytesLike],
    [bigint],
    "view"
  >;

  revokeCredential: TypedContractMethod<
    [credentialId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokedCredentials: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalCredentialsAnchored: TypedContractMethod<[], [bigint], "view">;

  totalInstitutions: TypedContractMethod<[], [bigint], "view">;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  version: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INSTITUTION_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addInstitution"
  ): TypedContractMethod<
    [institution: AddressLike, name: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "anchorCredentialBatch"
  ): TypedContractMethod<
    [merkleRoot: BytesLike, batchSize: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchCheckRevocation"
  ): TypedContractMethod<[credentialIds: BytesLike[]], [boolean[]], "view">;
  getFunction(
    nameOrSignature: "getInstitutionInfo"
  ): TypedContractMethod<
    [institution: AddressLike],
    [
      [string, boolean, bigint, bigint] & {
        name: string;
        active: boolean;
        registeredDate: bigint;
        totalCredentials: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMerkleRootInfo"
  ): TypedContractMethod<
    [merkleRoot: BytesLike],
    [
      [string, bigint, bigint] & {
        institution: string;
        batchSize: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRevocationTimestamp"
  ): TypedContractMethod<[credentialId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[admin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "institutions"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, boolean, bigint, bigint] & {
        name: string;
        active: boolean;
        registeredDate: bigint;
        totalCredentials: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isInstitution"
  ): TypedContractMethod<[institution: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRevoked"
  ): TypedContractMethod<[credentialId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "merkleRoots"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, boolean] & {
        institution: string;
        batchSize: bigint;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeInstitution"
  ): TypedContractMethod<[institution: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revocationTimestamps"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "revokeCredential"
  ): TypedContractMethod<
    [credentialId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokedCredentials"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalCredentialsAnchored"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalInstitutions"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CredentialBatchAnchored"
  ): TypedContractEvent<
    CredentialBatchAnchoredEvent.InputTuple,
    CredentialBatchAnchoredEvent.OutputTuple,
    CredentialBatchAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "CredentialRevoked"
  ): TypedContractEvent<
    CredentialRevokedEvent.InputTuple,
    CredentialRevokedEvent.OutputTuple,
    CredentialRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "InstitutionAdded"
  ): TypedContractEvent<
    InstitutionAddedEvent.InputTuple,
    InstitutionAddedEvent.OutputTuple,
    InstitutionAddedEvent.OutputObject
  >;
  getEvent(
    key: "InstitutionRemoved"
  ): TypedContractEvent<
    InstitutionRemovedEvent.InputTuple,
    InstitutionRemovedEvent.OutputTuple,
    InstitutionRemovedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "CredentialBatchAnchored(bytes32,address,uint256,uint256)": TypedContractEvent<
      CredentialBatchAnchoredEvent.InputTuple,
      CredentialBatchAnchoredEvent.OutputTuple,
      CredentialBatchAnchoredEvent.OutputObject
    >;
    CredentialBatchAnchored: TypedContractEvent<
      CredentialBatchAnchoredEvent.InputTuple,
      CredentialBatchAnchoredEvent.OutputTuple,
      CredentialBatchAnchoredEvent.OutputObject
    >;

    "CredentialRevoked(bytes32,address,string,uint256)": TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;
    CredentialRevoked: TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "InstitutionAdded(address,string,uint256)": TypedContractEvent<
      InstitutionAddedEvent.InputTuple,
      InstitutionAddedEvent.OutputTuple,
      InstitutionAddedEvent.OutputObject
    >;
    InstitutionAdded: TypedContractEvent<
      InstitutionAddedEvent.InputTuple,
      InstitutionAddedEvent.OutputTuple,
      InstitutionAddedEvent.OutputObject
    >;

    "InstitutionRemoved(address,uint256)": TypedContractEvent<
      InstitutionRemovedEvent.InputTuple,
      InstitutionRemovedEvent.OutputTuple,
      InstitutionRemovedEvent.OutputObject
    >;
    InstitutionRemoved: TypedContractEvent<
      InstitutionRemovedEvent.InputTuple,
      InstitutionRemovedEvent.OutputTuple,
      InstitutionRemovedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
