/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ICredentialRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "anchorCredentialBatch"
      | "getMerkleRootInfo"
      | "isInstitution"
      | "isRevoked"
      | "revokeCredential"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CredentialBatchAnchored"
      | "CredentialRevoked"
      | "InstitutionAdded"
      | "InstitutionRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "anchorCredentialBatch",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMerkleRootInfo",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isInstitution",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRevoked",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCredential",
    values: [BytesLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "anchorCredentialBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMerkleRootInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isInstitution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isRevoked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeCredential",
    data: BytesLike
  ): Result;
}

export namespace CredentialBatchAnchoredEvent {
  export type InputTuple = [
    merkleRoot: BytesLike,
    institution: AddressLike,
    batchSize: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    merkleRoot: string,
    institution: string,
    batchSize: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    merkleRoot: string;
    institution: string;
    batchSize: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialRevokedEvent {
  export type InputTuple = [
    credentialId: BytesLike,
    institution: AddressLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    credentialId: string,
    institution: string,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    credentialId: string;
    institution: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InstitutionAddedEvent {
  export type InputTuple = [
    institution: AddressLike,
    name: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    institution: string,
    name: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    institution: string;
    name: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InstitutionRemovedEvent {
  export type InputTuple = [institution: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [institution: string, timestamp: bigint];
  export interface OutputObject {
    institution: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ICredentialRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ICredentialRegistry;
  waitForDeployment(): Promise<this>;

  interface: ICredentialRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchorCredentialBatch: TypedContractMethod<
    [merkleRoot: BytesLike, batchSize: BigNumberish],
    [void],
    "nonpayable"
  >;

  getMerkleRootInfo: TypedContractMethod<
    [merkleRoot: BytesLike],
    [
      [string, bigint, bigint] & {
        institution: string;
        batchSize: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  isInstitution: TypedContractMethod<
    [institution: AddressLike],
    [boolean],
    "view"
  >;

  isRevoked: TypedContractMethod<[credentialId: BytesLike], [boolean], "view">;

  revokeCredential: TypedContractMethod<
    [credentialId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchorCredentialBatch"
  ): TypedContractMethod<
    [merkleRoot: BytesLike, batchSize: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMerkleRootInfo"
  ): TypedContractMethod<
    [merkleRoot: BytesLike],
    [
      [string, bigint, bigint] & {
        institution: string;
        batchSize: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isInstitution"
  ): TypedContractMethod<[institution: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRevoked"
  ): TypedContractMethod<[credentialId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "revokeCredential"
  ): TypedContractMethod<
    [credentialId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CredentialBatchAnchored"
  ): TypedContractEvent<
    CredentialBatchAnchoredEvent.InputTuple,
    CredentialBatchAnchoredEvent.OutputTuple,
    CredentialBatchAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "CredentialRevoked"
  ): TypedContractEvent<
    CredentialRevokedEvent.InputTuple,
    CredentialRevokedEvent.OutputTuple,
    CredentialRevokedEvent.OutputObject
  >;
  getEvent(
    key: "InstitutionAdded"
  ): TypedContractEvent<
    InstitutionAddedEvent.InputTuple,
    InstitutionAddedEvent.OutputTuple,
    InstitutionAddedEvent.OutputObject
  >;
  getEvent(
    key: "InstitutionRemoved"
  ): TypedContractEvent<
    InstitutionRemovedEvent.InputTuple,
    InstitutionRemovedEvent.OutputTuple,
    InstitutionRemovedEvent.OutputObject
  >;

  filters: {
    "CredentialBatchAnchored(bytes32,address,uint256,uint256)": TypedContractEvent<
      CredentialBatchAnchoredEvent.InputTuple,
      CredentialBatchAnchoredEvent.OutputTuple,
      CredentialBatchAnchoredEvent.OutputObject
    >;
    CredentialBatchAnchored: TypedContractEvent<
      CredentialBatchAnchoredEvent.InputTuple,
      CredentialBatchAnchoredEvent.OutputTuple,
      CredentialBatchAnchoredEvent.OutputObject
    >;

    "CredentialRevoked(bytes32,address,string,uint256)": TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;
    CredentialRevoked: TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;

    "InstitutionAdded(address,string,uint256)": TypedContractEvent<
      InstitutionAddedEvent.InputTuple,
      InstitutionAddedEvent.OutputTuple,
      InstitutionAddedEvent.OutputObject
    >;
    InstitutionAdded: TypedContractEvent<
      InstitutionAddedEvent.InputTuple,
      InstitutionAddedEvent.OutputTuple,
      InstitutionAddedEvent.OutputObject
    >;

    "InstitutionRemoved(address,uint256)": TypedContractEvent<
      InstitutionRemovedEvent.InputTuple,
      InstitutionRemovedEvent.OutputTuple,
      InstitutionRemovedEvent.OutputObject
    >;
    InstitutionRemoved: TypedContractEvent<
      InstitutionRemovedEvent.InputTuple,
      InstitutionRemovedEvent.OutputTuple,
      InstitutionRemovedEvent.OutputObject
    >;
  };
}
